name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "corretto"
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew assembleDebug
#      - uses: actions/upload-artifact@v4
#        with:
#          name: app-debug.apk
#          path: app/build/outputs/apk/debug/app-debug.apk
