name: Chores

on:
  schedule:
    - cron: '0 0 * * 2'   # Every Tuesday at 0 AM

  # Allow manual trigger
  workflow_dispatch:

# Prevent multiple jobs from running at the same time
concurrency:
  group: 'house-keeping'
  cancel-in-progress: false  # Don't cancel any in-progress runs in this group

jobs:
  remove-success-workflows:
    runs-on: ubuntu-latest
    env:
      # Repo's path in format {OWNER}/{REPO}
      GITHUB_REPOSITORY: ${{ github.action_repository }}
      # ref/heads/{branch}
      GITHUB_REF: ${{ github.ref }}

    # Inspired by this article https://devblog.jpcaparas.com/bulk-delete-github-actions-workflow-runs-with-a-simple-bash-function-b9105009a579
    # Each command is run on separated step for debug purpose
    steps:
      - name: Login to Github CLI
        run: echo "${{ secrets.HOUSE_KEEPER_WORKFLOW }}" | gh auth login --with-token

      - uses: actions/checkout@v5

      - name: Run script
        run: bash .github/delete_success_workflows.sh
