name: Fetch, create, and update repo's contributors

on:
  schedule:
    - cron: '0 23 * * 6'  # Every Saturday at 23 PM

  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-contributors-list:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit
      # and push the added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install BeautifulSoup4 dependency
        run: pip install beautifulsoup4 requests

      - uses: actions/checkout@v5

      - name: Run get_developers.py script
        env:
          # Repo's path in format {OWNER}/{REPO}
          GITHUB_REPOSITORY: ${{ github.action_repository }}
        run: python .github/get_developers.py

      - name: Copy generated contributors.json to its correct place
        run: "mv contributors.json composeApp/src/androidMain/res/raw/contributors.json"

      - name: Get current date
        id: date
        run: echo "date=$(date +'%m-%d-%Y')" >> $GITHUB_OUTPUT

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "In-app contributors list updated ${{ steps.date.outputs.date }}"