name: Weekly Android app deploy

on:
  schedule:
  # Gotta wait until contributors.json is updated
  - cron: '0 0 * * 2'  # Every Tuesday at 0AM

  # Allow manual trigger
  workflow_dispatch:

concurrency:
  group: 'Weekly-deploy'
  cancel-in-progress: false  # Don't cancel any in-progress runs in this group

jobs:
  setup:
    runs-on: ubuntu-latest
    # Set date as a variable
    outputs:
      BUILD_DATE: ${{ steps.date.outputs.date }}
      APK_FILENAME: app-foss-release-${{ steps.date.outputs.date }}.apk

    steps:
    - name: Get date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"

  build-apk:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.1

    - name: Setup Java 21
      uses: actions/setup-java@v4.4.0
      with:
        java-version: "21"
        distribution: "corretto"
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Rename to match build number
      run: |
        mkdir -p app

        cp composeApp/build/outputs/apk/foss/debug/app-foss-debug.apk app/${{ needs.setup.outputs.APK_FILENAME }}

    - name: Upload built artifact for next job
      uses: actions/upload-artifact@v4.4.1
      with:
        name: ${{ needs.setup.outputs.APK_FILENAME }}
        path: app/${{ needs.setup.outputs.APK_FILENAME }}


  upload-to-release:
    needs: [setup, build-apk]
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve APK
      uses: actions/download-artifact@v4.1.8
      with:
        name: ${{ needs.setup.outputs.APK_FILENAME }}

    - name: Upload built APK to release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ needs.setup.outputs.APK_FILENAME }}
        prerelease: true
        name: RiMusic Weekly Build | Custom Version | ${{ needs.setup.outputs.BUILD_DATE }}
        tag_name: "custom-version"
        body: |
          <div align="center">
            <img src="/assets/design/latest/app_logo.svg" width="300" height="100" />
            <p><b>RiMusic</b> Custom Version</p>
            <p>Remember, the custom version is not an official release.</p>
          </div>

          ## â— CUSTOM VERSION
          **WARNING**: This custom version is not an official release, it only serves to anticipate fix or feature pending the official release. Downloading only if invited by the developer, it may damage your current installation.

          ## ðŸ“² Installation

          > Android treats this installation as a different app and will not remove old RiMusic app.

          Download [HERE](https://github.com/knighthat/RiMusic/releases/download/custom-version/${{ needs.setup.outputs.APK_FILENAME }}) or use link down below

        token: ${{ secrets.RELEASE_TOKEN }}
        generate_release_notes: true
